name: Run Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install client dependencies
        run: bun install --cwd ./client

      - name: Start PostgreSQL
        run: sudo systemctl start postgresql.service

      - name: Create PostgreSQL User
        run: sudo -u postgres psql -c "CREATE ROLE \"user\" WITH LOGIN PASSWORD 'password' CREATEDB;"

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

      - name: Test
        run: bun run test